# Terminal 
# window_padding_width 10

# Font 
font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 14.0

# Cursor
cursor #B3E5FC
cursor_text_color #B3E5FC
shell_integration no-cursor
cursor_shape block
cursor_shape_unfocused hollow
cursor_blink_interval 0

# History
scrollback_lines 2500

# Other Tweaks
strip_trailing_spaces smart
enable_audio_bell no

# Background
background_opacity 0.5

# Advanced
allow_remote_control yes

# Keyboard Shortcuts
map alt+c copy_to_clipboard
map alt+v paste_from_clipboard
map alt+f5 load_config_file

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
